= java-archetype
:toc:
:toc-placement: preamble
:sectanchors:
:groupId: io.github.oliviercailloux
:artifactId: java-archetype
:repository: {artifactId}

image:https://travis-ci.com/oliviercailloux/{repository}.svg?branch=master["Build Status", link="https://travis-ci.com/oliviercailloux/{repository}"]
image:https://maven-badges.herokuapp.com/maven-central/{groupId}/{artifactId}/badge.svg["Artifact on Maven Central", link="http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22{groupId}%22%20a%3A%22{artifactId}%22"]

A maven https://maven.apache.org/guides/introduction/introduction-to-archetypes.html[archetype] for quickly starting Java projects.

== Usage

* Type `mvn archetype:generate -Dfilter=cailloux:`.
* Select this artifact (`io.github.oliviercailloux:java-archetype`) from the resulting list.
* Enter your desired `groupId` and `artifactId`, press enter to accept the suggested package name, enter to confirm.
** You have to change the suggested package name if the default one has invalid characters, such as hyphens! (Due to a https://issues.apache.org/jira/browse/ARCHETYPE-490[bug] in Maven archetypes, it seems difficult to support this use case. Please consider up-voting the bug, or commenting if you know anything relevant.)
* Your project gets created in a subfolder of your current position, named from your `artifactId`.

=== Other usages

* `mvn archetype:generate -DarchetypeGroupId=io.github.oliviercailloux -DarchetypeArtifactId=java-archetype` directly selects the right archetype.
** Use `org.apache.maven.plugins:maven-archetype-plugin:3.1.2:generate` instead of `archetype:generate` to use a specific (possibly more recent) version of the https://search.maven.org/artifact/org.apache.maven.plugins/maven-archetype-plugin[`archetype`] plugin
* `mvn archetype:generate -DarchetypeGroupId=io.github.oliviercailloux -DarchetypeArtifactId=java-archetype -DgroupId=mygroupid -DartifactId=myartifactid -DinteractiveMode=false` also indicates the desired group and artifact ids and remove the prompts.

=== From Eclipse
Eclipse looks at your local archetype catalog. You need to make this archetype appear there.

* Invoke this archetype using one of the commands above. Maven will download it in your local repository (you should now see it under `~/.m2/repository/io/github/oliviercailloux/`).
* `mvn archetype:crawl -Dcatalog=/home/username/.m2/archetype-catalog.xml` asks Maven to create (or update) your local archetype catalog (http://maven.40175.n5.nabble.com/archetype-catalog-xml-location-archetype-crawl-versus-archetype-generate-td113741.html[more] https://issues.apache.org/jira/browse/ARCHETYPE-142[info]).
* In Eclipse: `File` / `New` / `Maven Project`, select this archetype.

=== From Eclipse (alternatives)
The following procedure uses the remote archetype catalog instead of the local one. The drawback is that it takes about 15 seconds each time you want to use this archetype, as Eclipse downloads the (huge) remote archetype catalog again each time. (Tested with Eclipse Neon, Oxygen and Photon.)

* `Window` / `Preferences` / `Maven` / `Archetypes` / `Add Remote Catalog…`, give it the url http://repo1.maven.org/maven2/archetype-catalog.xml, Description: Remote archetypes catalog.
* `File` / `New` / `Maven Project`, type `cailloux` in the filter box. Select this archetype.

Instead of using the Maven local or remote archetypes catalog as indicated above, you may prefer the `Nexus Indexer`: `File` / `New` / `Maven Project`, select `Nexus Indexer` as a catalog, type `cailloux` in the filter box. Select this archetype. (Tested under Eclipse Oxygen.) (On my install nothing appeared under `Nexus Indexer`, by default. Follow link:Nexus%20Indexer%20from%20Eclipse.adoc[this] to solve that problem.)

== Generated projects
Projects generated from this archetype have the following characteristics.

* The https://github.com/oliviercailloux/java-archetype/blob/master/src/main/resources/archetype-resources/pom.xml[pom] has recent versions of:
** https://github.com/google/guava[Guava]
** http://www.slf4j.org/[SLF4J] with http://logback.qos.ch/[Logback].
* The project contains:
** a starter https://github.com/oliviercailloux/java-archetype/blob/master/src/main/resources/archetype-resources/src/main/java/App.java[class] with a main
** a JUnit test https://github.com/oliviercailloux/java-archetype/blob/master/src/main/resources/archetype-resources/src/test/java/MyTests.java[case]
** a configuration https://github.com/oliviercailloux/java-archetype/blob/master/src/main/resources/archetype-resources/src/main/resources/logback.xml[file] for Logback
** a https://github.com/oliviercailloux/java-archetype/blob/master/src/main/resources/archetype-resources/.gitignore[.gitignore] file.

== How it works

* I published this project to http://search.maven.org/#search|ga|1|g:io.github.oliviercailloux%20a:java-archetype[Maven Central] (source on Maven Central visible https://repo.maven.apache.org/maven2/io/github/oliviercailloux/java-archetype/[here]).
* A few days later, the https://repo1.maven.org/maven2/archetype-catalog.xml[remote archetypes catalog] indexed it.
* When starting the https://maven.apache.org/archetype/maven-archetype-plugin/generate-mojo.html[`archetype:generate`] goal, maven uses the `org.apache.maven.plugins:maven-archetype-plugin` plugin, which (by default) searches for archetypes in the remote archetypes catalog (see http://maven.apache.org/archetype/maven-archetype-plugin/specification/archetype-catalog.html[Archetype Catalog]).
* One week later than publication, the Maven http://maven.apache.org/repository/central-index.html[Central Index] was updated. (Thus, there might be a delay between availability from maven command line invocation and availability from within <<from-eclipse-neon,Eclipse>>, depending on the way you access archetypes.)

