= java-se-1.8-archetype
:toc:
:toc-placement: preamble
:sectanchors:

A maven https://maven.apache.org/guides/introduction/introduction-to-archetypes.html[archetype] for quickly starting Java SE 1.8 projects.

== Usage

* Type `mvn archetype:generate -Dfilter=cailloux:`.
* Select this artifact (`io.github.oliviercailloux:java-se-1.8-archetype`) from the resulting list.
* Enter your desired `groupId` and `artifactId`, press enter to accept the suggested package name, enter to confirm.
** You have to change the suggested package name if the default one has invalid characters, such as hyphens!
* Your project gets created in a subfolder of your current position, named from your `artifactId`.

=== Other usages

* `mvn archetype:generate -DarchetypeGroupId=io.github.oliviercailloux -DarchetypeArtifactId=java-se-1.8-archetype` directly selects the right archetype.
* `mvn archetype:generate -DarchetypeGroupId=io.github.oliviercailloux -DarchetypeArtifactId=java-se-1.8-archetype -DgroupId=mygroupid -DartifactId=myartifactid` also indicates the desired group and artifact ids.
** Unfortunately, using `-DinteractiveMode=false` for full automation does not work: the package directory becomes (literally) `${groupId}`. If you know how to solve this, please let me know.
* ``uuid=\`cat /proc/sys/kernel/random/uuid` ; mvn archetype:generate -DarchetypeGroupId=io.github.oliviercailloux -DarchetypeArtifactId=java-se-1.8-archetype -DgroupId=mygroupid -DartifactId=artifact_${uuid:0:3}`` in Bash, creates an artifact with a partly random id.

=== From Eclipse Neon

* `Window` / `Preferences` / `Maven` / `Archetypes` / `Add Remote Catalog…`, give it the url http://repo1.maven.org/maven2/archetype-catalog.xml, Description: Remote archetypes catalog.
* `File` / `New` / `Maven Project`, select `Remote archetypes catalog` as a catalog, type `cailloux` in the filter box. (It takes about 15 seconds to appear, on my older computer.) Select this archetype.
* Instead of using the Maven remote archetypes catalog, you may prefer the `Nexus Indexer`: `File` / `New` / `Maven Project`, select `Nexus Indexer` as a catalog, type `cailloux` in the filter box. Select this archetype.
** On my install nothing appeared under `Nexus Indexer`, by default. Follow link:Nexus%20Indexer%20from%20Eclipse.adoc[this] to solve that problem. (But I recommend rather using the Maven remote archetypes catalog.)

== Generated projects
Projects generated from this archetype have the following characteristics.

* The https://github.com/oliviercailloux/java-se-1.8-archetype/blob/master/src/main/resources/archetype-resources/pom.xml[pom] has latest versions of:
** https://github.com/google/guava[Guava]
** http://www.slf4j.org/[SLF4J] with http://logback.qos.ch/[Logback].
* The project contains:
** a starter https://github.com/oliviercailloux/java-se-1.8-archetype/blob/master/src/main/resources/archetype-resources/src/main/java/App.java[class] with a main
** a configuration https://github.com/oliviercailloux/java-se-1.8-archetype/blob/master/src/main/resources/archetype-resources/src/main/resources/logback.xml[file] for Logback
** a https://github.com/oliviercailloux/java-se-1.8-archetype/blob/master/src/main/resources/archetype-resources/.gitignore[.gitignore] file.

== How it works

* I published this project to http://search.maven.org/#search|ga|1|g:io.github.oliviercailloux%20a:java-se-1.8-archetype[Maven Central] (source on Maven Central visible https://repo.maven.apache.org/maven2/io/github/oliviercailloux/java-se-1.8-archetype/[here]).
* A few days later, the http://repo1.maven.org/maven2/archetype-catalog.xml[remote archetypes catalog] indexed it.
* When starting the https://maven.apache.org/archetype/maven-archetype-plugin/generate-mojo.html[`archetype:generate`] goal, maven uses the `org.apache.maven.plugins:maven-archetype-plugin` plugin, which (by default) searches for archetypes in the remote archetypes catalog (see http://maven.apache.org/archetype/maven-archetype-plugin/specification/archetype-catalog.html[Archetype Catalog]).
* One week later than publication, the Maven Central http://central.maven.org/maven2/.index/[Nexus Indexer] indexed it.
* The indexing process from Eclipse (see <<from-eclipse-neon,above>>) relies (according to my observation) on that Indexer, hence there might be a delay between availability from maven command line invocation and availability from within Eclipse.

